# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nuther < Formula
  desc "S.M.A.R.T. disk health monitoring TUI"
  homepage "https://github.com/lugnicca/nuther"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lugnicca/nuther/releases/download/v0.1.2/nuther_0.1.2_darwin_amd64.tar.gz"
      sha256 "a9344a55ed288273a8bbf4e6c6cac72268500dc1183a8d26ffd7ce7697152c23"

      def install
        bin.install "nuther"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lugnicca/nuther/releases/download/v0.1.2/nuther_0.1.2_darwin_arm64.tar.gz"
      sha256 "d32bf2b972707c873226bd4e6322ab969fd04688482cb85116f555335ff50eb5"

      def install
        bin.install "nuther"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lugnicca/nuther/releases/download/v0.1.2/nuther_0.1.2_linux_amd64.tar.gz"
      sha256 "2d9741eeaaa07bbb138d83d14edd543b97bc4e6f2ebc66fdeb7fff25a47bdf1f"
      def install
        bin.install "nuther"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lugnicca/nuther/releases/download/v0.1.2/nuther_0.1.2_linux_arm64.tar.gz"
      sha256 "27c14a1559046088169f9529875a9a8f8f528a93e7f2f686cf739998421e22e7"
      def install
        bin.install "nuther"
      end
    end
  end

  test do
    system "#{bin}/nuther", "--version"
  end
end
