# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nuther < Formula
  desc "S.M.A.R.T. disk health monitoring TUI"
  homepage "https://github.com/lugnicca/nuther"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lugnicca/nuther/releases/download/v0.2.1/nuther_0.2.1_darwin_amd64.tar.gz"
      sha256 "6f6ad92eec3690e3aca48096900277dd67d7e7b7230842de9fa1f960dfcbd24b"

      define_method(:install) do
        bin.install "nuther"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lugnicca/nuther/releases/download/v0.2.1/nuther_0.2.1_darwin_arm64.tar.gz"
      sha256 "4059b6329e442ebc1033553b3e1b0dc8f06ce03aa37496cc0739e1edec591066"

      define_method(:install) do
        bin.install "nuther"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lugnicca/nuther/releases/download/v0.2.1/nuther_0.2.1_linux_amd64.tar.gz"
      sha256 "ca34657535d32914ed3c6ecaf23844621bb389e877f3631cd95815c66927ec5d"
      define_method(:install) do
        bin.install "nuther"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lugnicca/nuther/releases/download/v0.2.1/nuther_0.2.1_linux_arm64.tar.gz"
      sha256 "540ddcc4dfedb926f97f28f02a814998b1506354a8a07ba044b2e7060667e58f"
      define_method(:install) do
        bin.install "nuther"
      end
    end
  end

  test do
    system "#{bin}/nuther", "--version"
  end
end
