# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nuther < Formula
  desc "S.M.A.R.T. disk health monitoring TUI"
  homepage "https://github.com/lugnicca/nuther"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lugnicca/nuther/releases/download/v0.2.0/nuther_0.2.0_darwin_amd64.tar.gz"
      sha256 "6d2ab9e47e8521ed6d5400f5bfb47bd8620a5b925881251717c5937825862287"

      define_method(:install) do
        bin.install "nuther"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lugnicca/nuther/releases/download/v0.2.0/nuther_0.2.0_darwin_arm64.tar.gz"
      sha256 "040fad6af6970a6f5eb3734f8af060b7e953b7a6ce58c14b0a8405efad522954"

      define_method(:install) do
        bin.install "nuther"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lugnicca/nuther/releases/download/v0.2.0/nuther_0.2.0_linux_amd64.tar.gz"
      sha256 "81ef68e358f7c82082a0a589107b06fd75768ecb74901cc8291fa32063045c2a"
      define_method(:install) do
        bin.install "nuther"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lugnicca/nuther/releases/download/v0.2.0/nuther_0.2.0_linux_arm64.tar.gz"
      sha256 "13ecb16d31dc9e13f8b8bc7965b69046158b2face14fe461e743575c8207ab06"
      define_method(:install) do
        bin.install "nuther"
      end
    end
  end

  test do
    system "#{bin}/nuther", "--version"
  end
end
